/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.*;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author thisajamudalige
 */
public class CartView extends javax.swing.JFrame {

    /**
     * Creates new form CartView
     */
    public CartView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabCart = new javax.swing.JTable();
        btnViewCart = new javax.swing.JButton();
        btnOrderNow = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        labHome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labUname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(690, 430));
        getContentPane().setLayout(null);

        jScrollPane1.setForeground(new java.awt.Color(0, 102, 0));

        tabCart.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tabCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(tabCart);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(47, 89, 590, 251);

        btnViewCart.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        btnViewCart.setForeground(new java.awt.Color(0, 102, 0));
        btnViewCart.setText("View Cart");
        btnViewCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewCart);
        btnViewCart.setBounds(543, 58, 94, 25);

        btnOrderNow.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        btnOrderNow.setForeground(new java.awt.Color(0, 102, 0));
        btnOrderNow.setText("Order Now");
        btnOrderNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderNowActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrderNow);
        btnOrderNow.setBounds(372, 358, 190, 25);

        btnCancel.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 102, 0));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(121, 358, 190, 25);

        labHome.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/pngwingcom-1 (3).png")); // NOI18N
        labHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labHomeMouseClicked(evt);
            }
        });
        getContentPane().add(labHome);
        labHome.setBounds(40, 10, 80, 75);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Your Cart");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 30, 110, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/3406f4103503643-1-2-3 (9).jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 690, 420);
        getContentPane().add(labUname);
        labUname.setBounds(582, 10, 90, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labHomeMouseClicked
        // TODO add your handling code here:
        
        String Uname=labUname.getText().trim();
        
        HomeView HV = new HomeView();
        HV.labUname.setText(Uname);
        HV.setVisible(true);
        dispose();
    }//GEN-LAST:event_labHomeMouseClicked

    private void btnOrderNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderNowActionPerformed
        // TODO add your handling code here:
        
        String Uname=labUname.getText().trim();
        try 
        {
            Statement st=MyDBConn.getMyDBCon().createStatement();
            
            ResultSet resultSet = st.executeQuery("SELECT COUNT(*) FROM Cart WHERE Username='"+Uname+"'");
            resultSet.next(); 
            
            int rowCount = resultSet.getInt(1);

            if (rowCount > 0) 
            { 
                try
                {
                    Statement st1 = MyDBConn.getMyDBCon().createStatement(); 
                    String sql = "SELECT SUM(ItemPrice) FROM Cart WHERE Username='"+Uname+"'";
                    ResultSet rs = st1.executeQuery(sql);

                    if (rs.next()) 
                    {
                        double total = rs.getDouble(1); 
                        
                        OrderView OV = new OrderView();
                        OV.labTotal.setText(String.valueOf(total));
                        OV.labUname.setText(Uname);
                        OV.setVisible(true);
                        dispose();
                    }

                    rs.close();
                    st1.close();
                }
                catch (Exception e) 
                {
                    JOptionPane.showMessageDialog(null,e.getMessage());
                }
               
            } 
            else 
            {
                JOptionPane.showMessageDialog(null,"Your cart is already empty.");
            }
            resultSet.close();
        } 
        
        catch (Exception e) 
        {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btnOrderNowActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        String Uname=labUname.getText().trim();
        
        try 
        {
            Statement st=MyDBConn.getMyDBCon().createStatement();
            String sql = "DELETE FROM Cart WHERE Username='"+Uname+"'";
            
            st.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(null, "Your cart is droped");
            
            HomeView HV = new HomeView();
            HV.labUname.setText(Uname);
            HV.setVisible(true);
            dispose();
        } 
        catch (Exception e) 
        {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnViewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCartActionPerformed
        // TODO add your handling code here:
        String Uname=labUname.getText().trim();
        
        try
        {
            Statement st=MyDBConn.getMyDBCon().createStatement();
            String sql="SELECT * from Cart WHERE Username='"+Uname+"'";
            ResultSet rs=st.executeQuery(sql);
            
            while(rs.next())
            {
                String ItemName = rs.getString("ItemName");
                String ItemQty = String.valueOf(rs.getInt("ItemQty"));
                String ItemPrice = String.valueOf(rs.getInt("ItemPrice"));
                
                String Cart[]={ItemName,ItemQty,ItemPrice};
                DefaultTableModel tbl = (DefaultTableModel) tabCart.getModel();
                
                tbl.addRow(Cart);
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        
        btnViewCart.setEnabled(false);
    }//GEN-LAST:event_btnViewCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOrderNow;
    private javax.swing.JButton btnViewCart;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labHome;
    public javax.swing.JLabel labUname;
    private javax.swing.JTable tabCart;
    // End of variables declaration//GEN-END:variables
}
