/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author thisajamudalige
 */
public class CreateAccView extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccView
     */
    public CreateAccView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JSpinner();
        txtFname = new javax.swing.JTextField();
        txtConPass = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labLogin = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPNum = new javax.swing.JTextField();
        txtUname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAdd = new javax.swing.JTextArea();
        rbtnFemale = new javax.swing.JRadioButton();
        rbtnMale = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(574, 668));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Full Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 90, 67, 19);

        txtDOB.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(-600072240000L), new java.util.Date(), java.util.Calendar.DAY_OF_YEAR));
        getContentPane().add(txtDOB);
        txtDOB.setBounds(250, 200, 290, 30);
        getContentPane().add(txtFname);
        txtFname.setBounds(250, 110, 290, 30);
        getContentPane().add(txtConPass);
        txtConPass.setBounds(250, 540, 290, 30);
        txtConPass.getAccessibleContext().setAccessibleName("");

        getContentPane().add(txtPass);
        txtPass.setBounds(250, 480, 290, 30);
        txtPass.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date of Birth");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 180, 84, 19);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 240, 57, 19);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email (@gmail.com)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 400, 140, 19);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone Number (Sri Lanka)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 340, 180, 19);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password (least 8 characters)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 460, 200, 19);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 400, 69, 19);

        labLogin.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        labLogin.setForeground(new java.awt.Color(0, 102, 0));
        labLogin.setText("<LOGIN");
        labLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labLoginMouseClicked(evt);
            }
        });
        getContentPane().add(labLogin);
        labLogin.setBounds(10, 10, 70, 19);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Create an Account");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 40, 168, 24);

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Confirm Password");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(250, 520, 125, 19);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(250, 420, 139, 30);
        getContentPane().add(txtPNum);
        txtPNum.setBounds(250, 360, 290, 30);
        getContentPane().add(txtUname);
        txtUname.setBounds(400, 420, 139, 30);

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        txtAdd.setColumns(20);
        txtAdd.setRows(3);
        jScrollPane1.setViewportView(txtAdd);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 260, 290, 69);

        Gender.add(rbtnFemale);
        rbtnFemale.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        rbtnFemale.setForeground(new java.awt.Color(255, 255, 255));
        rbtnFemale.setText("Female");
        getContentPane().add(rbtnFemale);
        rbtnFemale.setBounds(360, 150, 72, 23);

        Gender.add(rbtnMale);
        rbtnMale.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        rbtnMale.setForeground(new java.awt.Color(255, 255, 255));
        rbtnMale.setText("Male");
        rbtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMaleActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnMale);
        rbtnMale.setBounds(250, 150, 55, 23);

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 0));
        jButton1.setText("Create an Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 600, 290, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/pngwingcom-2 (1).png")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 240, 160, 160);

        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/7abeb6103503643 (2).png")); // NOI18N
        jLabel11.setText("jLabel3");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-500, 0, 1180, 490);

        jLabel12.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/7abeb6103503643 (2).png")); // NOI18N
        jLabel12.setText("jLabel3");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-500, 470, 1180, 200);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMaleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String Fname = txtFname.getText().trim();
        String PATTERN = "^[A-Za-z ]+$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(Fname);
        
        if (!match.matches()) 
        {
            JOptionPane.showMessageDialog(null, "Invalid Full Name. Please enter again.");
            return; 
        }

        String genders ="";
        
        if (rbtnMale.isSelected()) 
        {
            genders = "Male";
        } 
        else if (rbtnFemale.isSelected()) 
        {
            genders = "Female";
        } 
        else 
        {
            JOptionPane.showMessageDialog(null, "Please select a gender");
            return; 
        }

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dobText = dateFormat.format((Date) txtDOB.getValue());
        
        String Add = txtAdd.getText().trim();
        
        if (Add.isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Address can't be blank. Please enter an Address.");
            return; 
        }
        
        String PNumText = txtPNum.getText().trim();
        String phonePattern = "^\\d{10}$";
        Pattern patt1 = Pattern.compile(phonePattern);
        Matcher match1 = patt1.matcher(PNumText);

        if (PNumText.isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Phone number can't be blank. Please enter a phone number.");
            return;
        }
        
        if (PNumText.charAt(0) != '0'|| !match1.matches()) 
        {
            JOptionPane.showMessageDialog(null, "Invalid Phone Number. Please enter a valid number.");
            return;
        }
        
        int PNum = Integer.parseInt(PNumText);
        
        String Email = txtEmail.getText().trim();
        
        if (Email.isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Email can't be blank. Please enter Email");
            return;
        } 
        
        String Uname = txtUname.getText().trim();
        
        if (Uname.isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Username can't be blank. Please enter Username");
            return;
        } 
        
        String Pass = txtPass.getText().trim();
        
        if (Pass.isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Password can't be blank. Please enter password");
            return;
        } 
        else if (Pass.length() < 8) 
        {
            JOptionPane.showMessageDialog(null, "Password must have at least 8 characters");
            return;
        }

        String Cpass = txtConPass.getText().trim();
        if (!Cpass.equals(Pass)) 
        {
            JOptionPane.showMessageDialog(null, "Passwords do not match");
            return;
        }
        
        try
        {
            Account acc = new Account();
            acc.CreateAcc(Fname,genders,dobText,Add,PNum,Email,Uname,Pass);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void labLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labLoginMouseClicked
        // TODO add your handling code here:
        LoginView LV=new LoginView();
        LV.show();
        dispose();
    }//GEN-LAST:event_labLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labLogin;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JTextArea txtAdd;
    private javax.swing.JTextField txtConPass;
    private javax.swing.JSpinner txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtPNum;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
