/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import Model.MyDBConn;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author thisajamudalige
 */
public class EditAccView extends javax.swing.JFrame {

    /**
     * Creates new form EditAccView
     */
    public EditAccView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeleteAcc = new javax.swing.JButton();
        labHome = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEditNum = new javax.swing.JTextField();
        txtEditFname = new javax.swing.JTextField();
        txtEditEmail = new javax.swing.JTextField();
        txtEditPass = new javax.swing.JTextField();
        txtEditConfPass = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEditAdd = new javax.swing.JTextArea();
        btnEditAcc = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        labUname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(578, 540));
        getContentPane().setLayout(null);

        btnDeleteAcc.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        btnDeleteAcc.setForeground(new java.awt.Color(0, 102, 0));
        btnDeleteAcc.setText("Delete Account");
        btnDeleteAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteAcc);
        btnDeleteAcc.setBounds(30, 460, 160, 30);

        labHome.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/pngwingcom-1 (3).png")); // NOI18N
        labHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labHomeMouseClicked(evt);
            }
        });
        getContentPane().add(labHome);
        labHome.setBounds(350, 20, 80, 75);

        btnLogOut.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(0, 102, 0));
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut);
        btnLogOut.setBounds(250, 460, 130, 30);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Edit Account");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 150, 40);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Email (@gmail.com) :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 290, 140, 30);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Password :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 340, 80, 30);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 0));
        jLabel5.setText("Confirm Password :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(53, 390, 140, 30);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Phone Number :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 239, 110, 30);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 0));
        jLabel7.setText("Address :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 160, 70, 19);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setText("Full Name :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 109, 80, 30);
        getContentPane().add(txtEditNum);
        txtEditNum.setBounds(250, 240, 290, 30);
        getContentPane().add(txtEditFname);
        txtEditFname.setBounds(250, 110, 290, 30);
        getContentPane().add(txtEditEmail);
        txtEditEmail.setBounds(250, 290, 290, 30);
        getContentPane().add(txtEditPass);
        txtEditPass.setBounds(250, 340, 290, 30);
        getContentPane().add(txtEditConfPass);
        txtEditConfPass.setBounds(250, 390, 290, 30);

        txtEditAdd.setColumns(20);
        txtEditAdd.setRows(2);
        jScrollPane1.setViewportView(txtEditAdd);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 160, 290, 60);

        btnEditAcc.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        btnEditAcc.setForeground(new java.awt.Color(0, 102, 0));
        btnEditAcc.setText("Edit Account");
        btnEditAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAccActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditAcc);
        btnEditAcc.setBounds(410, 460, 130, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/7abeb6103503643 (2).png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-490, 0, 1070, 520);

        labUname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labUname);
        labUname.setBounds(470, 10, 100, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAccActionPerformed
        // TODO add your handling code here:
        
        String Fname = txtEditFname.getText().trim();
        String PATTERN = "^[A-Za-z ]+$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(Fname);
        
        if (!match.matches()) 
        {
            JOptionPane.showMessageDialog(null, "Invalid Full Name. Please enter again.");
            return; 
        }
        
        String Add = txtEditAdd.getText().trim();
        
        if (Add.isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Please enter an Address.");
            return; 
        }
        
        String PNumText = txtEditNum.getText().trim();
        String phonePattern = "^\\d{10}$";
        Pattern patt1 = Pattern.compile(phonePattern);
        Matcher match1 = patt1.matcher(PNumText);

        if (PNumText.isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Phone number can't be blank. Please enter a phone number.");
            return;
        }
        
        if (PNumText.charAt(0) != '0'|| !match1.matches()) 
        {
            JOptionPane.showMessageDialog(null, "Invalid Phone Number. Please enter a valid number.");
            return;
        }
        
        int PNum = Integer.parseInt(PNumText);
        
        String Email = txtEditEmail.getText().trim();
        
        if (Email.isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Please enter Email");
            return;
        }
        
        String Pass = txtEditPass.getText().trim();
        
        if (Pass.isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Please enter password");
            return;
        } 
        if (Pass.length() < 8) 
        {
            JOptionPane.showMessageDialog(null, "Password must have at least 8 characters");
            return;
        }
        
        String Cpass = txtEditConfPass.getText().trim();
        
        if (!Cpass.equals(Pass)) 
        {
            JOptionPane.showMessageDialog(null, "Passwords do not match");
            return;
        }
        
        String Uname =labUname.getText().trim();
        
        try
        {
            Edit Ed = new Edit();
            Ed.EditAcc(Fname,Add,PNum,Email,Pass,Uname);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
        dispose();
    }//GEN-LAST:event_btnEditAccActionPerformed

    private void labHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labHomeMouseClicked
        // TODO add your handling code here:
        String Uname =labUname.getText().trim();
        
        HomeView HV = new HomeView();
        HV.labUname.setText(Uname);
        HV.setVisible(true); 
        dispose();
    }//GEN-LAST:event_labHomeMouseClicked

    private void btnDeleteAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccActionPerformed
        // TODO add your handling code here:
        String Uname =labUname.getText().trim();
        
        try 
        {
            Statement st=MyDBConn.getMyDBCon().createStatement();
            String sql = "DELETE FROM CustomerD WHERE CUserName='"+Uname+"'";
            
            st.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(null,"Your account deleted successfuly");
            
            LoginView LV = new LoginView();
            LV.show();
            dispose(); 
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }//GEN-LAST:event_btnDeleteAccActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        
        String Uname =labUname.getText().trim();
        
        try 
        {
            Statement st=MyDBConn.getMyDBCon().createStatement();
            String sql = "DELETE FROM Cart WHERE Username='"+Uname+"'";
            
            st.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(null,"You have been logged out successfuly");
            
            LoginView LV = new LoginView();
            LV.show();
            dispose();
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAccView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAccView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAccView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAccView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAccView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteAcc;
    private javax.swing.JButton btnEditAcc;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labHome;
    public javax.swing.JLabel labUname;
    private javax.swing.JTextArea txtEditAdd;
    private javax.swing.JTextField txtEditConfPass;
    private javax.swing.JTextField txtEditEmail;
    private javax.swing.JTextField txtEditFname;
    private javax.swing.JTextField txtEditNum;
    private javax.swing.JTextField txtEditPass;
    // End of variables declaration//GEN-END:variables
}
