/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import Model.MyDBConn;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author thisajamudalige
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        UpDownQty2 = new javax.swing.JSpinner();
        UpDownQty3 = new javax.swing.JSpinner();
        UpDownQty4 = new javax.swing.JSpinner();
        UpDownQty5 = new javax.swing.JSpinner();
        UpDownQty6 = new javax.swing.JSpinner();
        UpDownQty7 = new javax.swing.JSpinner();
        UpDownQty8 = new javax.swing.JSpinner();
        UpDownQty1 = new javax.swing.JSpinner();
        btnAddCart1 = new javax.swing.JButton();
        btnAddCart2 = new javax.swing.JButton();
        btnAddCart3 = new javax.swing.JButton();
        btnAddCart4 = new javax.swing.JButton();
        btnAddCart5 = new javax.swing.JButton();
        btnAddCart6 = new javax.swing.JButton();
        btnAddCart7 = new javax.swing.JButton();
        Report = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        btnAddCart8 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        labProfile = new javax.swing.JLabel();
        labCart = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        labUname = new javax.swing.JLabel();

        jLabel12.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/NIBM Notes/EAD/EAD Project/3cc41bf716067ad1505d99386c1173fb (1).jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(682, 810));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        UpDownQty2.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        UpDownQty2.setOpaque(true);
        getContentPane().add(UpDownQty2);
        UpDownQty2.setBounds(520, 160, 90, 23);

        UpDownQty3.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        UpDownQty3.setOpaque(true);
        getContentPane().add(UpDownQty3);
        UpDownQty3.setBounds(190, 330, 90, 23);

        UpDownQty4.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        UpDownQty4.setOpaque(true);
        getContentPane().add(UpDownQty4);
        UpDownQty4.setBounds(520, 330, 90, 23);

        UpDownQty5.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        UpDownQty5.setOpaque(true);
        getContentPane().add(UpDownQty5);
        UpDownQty5.setBounds(150, 510, 90, 23);

        UpDownQty6.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        UpDownQty6.setOpaque(true);
        getContentPane().add(UpDownQty6);
        UpDownQty6.setBounds(480, 510, 90, 23);

        UpDownQty7.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        UpDownQty7.setOpaque(true);
        getContentPane().add(UpDownQty7);
        UpDownQty7.setBounds(160, 680, 90, 23);

        UpDownQty8.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        UpDownQty8.setOpaque(true);
        getContentPane().add(UpDownQty8);
        UpDownQty8.setBounds(480, 680, 90, 23);

        UpDownQty1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        UpDownQty1.setOpaque(true);
        getContentPane().add(UpDownQty1);
        UpDownQty1.setBounds(190, 160, 90, 23);

        btnAddCart1.setForeground(new java.awt.Color(0, 102, 0));
        btnAddCart1.setText("Add to Cart");
        btnAddCart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCart1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCart1);
        btnAddCart1.setBounds(190, 190, 120, 23);

        btnAddCart2.setForeground(new java.awt.Color(0, 102, 0));
        btnAddCart2.setText("Add to Cart");
        btnAddCart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCart2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCart2);
        btnAddCart2.setBounds(520, 190, 120, 23);

        btnAddCart3.setForeground(new java.awt.Color(0, 102, 0));
        btnAddCart3.setText("Add to Cart");
        btnAddCart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCart3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCart3);
        btnAddCart3.setBounds(190, 370, 120, 23);

        btnAddCart4.setForeground(new java.awt.Color(0, 102, 0));
        btnAddCart4.setText("Add to Cart");
        btnAddCart4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCart4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCart4);
        btnAddCart4.setBounds(520, 370, 120, 23);

        btnAddCart5.setForeground(new java.awt.Color(0, 102, 0));
        btnAddCart5.setText("Add to Cart");
        btnAddCart5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCart5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCart5);
        btnAddCart5.setBounds(150, 550, 160, 23);

        btnAddCart6.setForeground(new java.awt.Color(0, 102, 0));
        btnAddCart6.setText("Add to Cart");
        btnAddCart6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCart6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCart6);
        btnAddCart6.setBounds(480, 550, 160, 23);

        btnAddCart7.setForeground(new java.awt.Color(0, 102, 0));
        btnAddCart7.setText("Add to Cart");
        btnAddCart7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCart7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCart7);
        btnAddCart7.setBounds(160, 720, 150, 23);

        Report.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/feedback-813419.png")); // NOI18N
        Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportMouseClicked(evt);
            }
        });
        getContentPane().add(Report);
        Report.setBounds(530, 20, 25, 30);

        jLabel44.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/pngwingcom-1 copy 4.png")); // NOI18N
        getContentPane().add(jLabel44);
        jLabel44.setBounds(240, 0, 70, 70);

        btnAddCart8.setForeground(new java.awt.Color(0, 102, 0));
        btnAddCart8.setText("Add to Cart");
        btnAddCart8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCart8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCart8);
        btnAddCart8.setBounds(480, 720, 160, 23);

        jLabel43.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/pngwingcom.png")); // NOI18N
        getContentPane().add(jLabel43);
        jLabel43.setBounds(250, 10, 200, 50);

        labProfile.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/user-1144760.png")); // NOI18N
        labProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labProfileMouseClicked(evt);
            }
        });
        getContentPane().add(labProfile);
        labProfile.setBounds(630, 20, 30, 30);

        labCart.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/shopping-cart-2838895.png")); // NOI18N
        labCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labCartMouseClicked(evt);
            }
        });
        getContentPane().add(labCart);
        labCart.setBounds(580, 20, 30, 30);

        jLabel33.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel33.setText("Rs1000");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(190, 140, 49, 18);

        jLabel34.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel34.setText("Rs900");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(520, 140, 41, 18);

        jLabel35.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel35.setText("Rs800");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(190, 300, 41, 18);

        jLabel36.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel36.setText("Rs950");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(520, 310, 41, 18);

        jLabel37.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel37.setText("Rs850");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(150, 480, 41, 18);

        jLabel38.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel38.setText("Rs600");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(480, 490, 41, 18);

        jLabel39.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel39.setText("Rs800");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(160, 660, 41, 18);

        jLabel40.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel40.setText("Rs700");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(480, 650, 41, 18);

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 0));
        jLabel21.setText("Sausage and Egg  ");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(190, 90, 130, 30);

        jLabel29.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 0));
        jLabel29.setText("Sandwich");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(190, 110, 80, 30);

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 0));
        jLabel22.setText("Bacon Sandwich");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(520, 120, 109, 18);

        jLabel30.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 0));
        jLabel30.setText("Double Smoked ");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(520, 100, 105, 18);

        jLabel23.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 0));
        jLabel23.setText("Egg Sandwich");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(190, 280, 92, 18);

        jLabel25.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 0));
        jLabel25.setText("Sandwich");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(520, 290, 63, 18);

        jLabel31.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 0));
        jLabel31.setText("Turkey Bacon ");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(520, 270, 93, 18);

        jLabel32.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 102, 0));
        jLabel32.setText("Cold Brew");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(480, 470, 67, 18);

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 0));
        jLabel24.setText("Iced Matcha Latte");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(150, 460, 116, 18);

        jLabel26.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 0));
        jLabel26.setText("CInnamon Caramel  Cream ");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(480, 450, 179, 18);

        jLabel27.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 0));
        jLabel27.setText("Iced Mango Latte");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(160, 640, 112, 18);

        jLabel28.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 0));
        jLabel28.setText("White Chocolate Mocha");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(480, 630, 153, 20);

        jLabel13.setForeground(new java.awt.Color(0, 102, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/5d6a62acb7ec8e2539fad4880e352370.jpg")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(360, 80, 140, 140);

        jLabel14.setForeground(new java.awt.Color(0, 102, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/5fa6a3b61d7d8a09bbf2bba6b3c6b5da.jpg")); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 260, 140, 140);

        jLabel15.setForeground(new java.awt.Color(0, 102, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/dc9d5f292b0ad066f932e5db7fee35f6.jpg")); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(360, 260, 140, 140);

        jLabel16.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/20210726-ibaraki.jpg")); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 440, 90, 140);

        jLabel17.setForeground(new java.awt.Color(0, 102, 0));
        jLabel17.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/20210726-tokyo.jpg")); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(360, 440, 140, 140);

        jLabel18.setForeground(new java.awt.Color(0, 102, 0));
        jLabel18.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/55cdbe4eaed7fe70c917bb909cb6f924.jpg")); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 620, 140, 140);

        jLabel19.setForeground(new java.awt.Color(0, 102, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/229813f1a41e4cd88b4593957c51ee05.jpg")); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(360, 620, 140, 140);

        jLabel20.setForeground(new java.awt.Color(0, 102, 0));
        jLabel20.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/3cc41bf716067ad1505d99386c1173fb.jpg")); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(30, 80, 140, 140);

        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/background-1 (1).jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 250, 312, 160);

        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/background-1 (1).jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 250, 312, 160);

        jLabel7.setForeground(new java.awt.Color(0, 102, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/background-1 (1).jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 430, 312, 160);

        jLabel9.setForeground(new java.awt.Color(0, 102, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/background-1 (1).jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 430, 312, 160);

        jLabel10.setForeground(new java.awt.Color(0, 102, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/background-1 (1).jpg")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(350, 610, 312, 160);

        jLabel11.setForeground(new java.awt.Color(0, 102, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/background-1 (1).jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 610, 312, 160);

        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/background-1 (1).jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 70, 312, 160);

        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/background-1 (1).jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 312, 160);

        jLabel42.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/3406f4103503643-1-2-2 (1).jpg")); // NOI18N
        getContentPane().add(jLabel42);
        jLabel42.setBounds(0, 400, 690, 410);

        jLabel41.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/3406f4103503643-1-2-3 (9).jpg")); // NOI18N
        getContentPane().add(jLabel41);
        jLabel41.setBounds(0, 0, 690, 420);
        getContentPane().add(labUname);
        labUname.setBounds(0, 0, 90, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labCartMouseClicked
        // TODO add your handling code here:
        String Uname=labUname.getText().trim();
        
        CartView CV = new CartView();
        CV.labUname.setText(Uname);
        CV.setVisible(true);
        dispose();
    }//GEN-LAST:event_labCartMouseClicked

    private void labProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labProfileMouseClicked
        // TODO add your handling code here:
        String Uname=labUname.getText().trim();
        
        EditAccView EA1 = new EditAccView();
        EA1.labUname.setText(Uname);
        EA1.setVisible(true);
        dispose();
    }//GEN-LAST:event_labProfileMouseClicked

    private void btnAddCart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCart1ActionPerformed
        // TODO add your handling code here:
        
        String Item="Sausage and Egg Sandwich";
        int qty=(int)UpDownQty1.getValue();
        String Uname=labUname.getText().trim();
        int total;
        
        total=1000*qty;
        
        try
        {
            Home H = new Home();
            H.AddCart(Item,qty,total,Uname);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        
        dispose();
        
    }//GEN-LAST:event_btnAddCart1ActionPerformed

    private void btnAddCart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCart2ActionPerformed
        // TODO add your handling code here:
        
        String Item="Double Smoked Bacon Sandwich";
        int qty=(int)UpDownQty2.getValue();
        String Uname=labUname.getText().trim();
        int total;
        
        total=900*qty;
        
        try
        {
            Home H = new Home();
            H.AddCart(Item,qty,total,Uname);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        
        dispose();
    }//GEN-LAST:event_btnAddCart2ActionPerformed

    private void btnAddCart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCart3ActionPerformed
        // TODO add your handling code here:
        
        String Item="Egg Sandwich";
        int qty=(int)UpDownQty3.getValue();
        String Uname=labUname.getText().trim();
        int total;
        
        total=800*qty;
        
        try
        {
            Home H = new Home();
            H.AddCart(Item,qty,total,Uname);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        
        dispose();
    }//GEN-LAST:event_btnAddCart3ActionPerformed

    private void btnAddCart4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCart4ActionPerformed
        // TODO add your handling code here:
        
        String Item="Turkey Bacon Sandwich";
        int qty=(int)UpDownQty4.getValue();
        String Uname=labUname.getText().trim();
        int total;
        
        total=950*qty;
        
        try
        {
            Home H = new Home();
            H.AddCart(Item,qty,total,Uname);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        
        dispose();
    }//GEN-LAST:event_btnAddCart4ActionPerformed

    private void btnAddCart5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCart5ActionPerformed
        // TODO add your handling code here:
        
        String Item="Iced Matcha Latte";
        int qty=(int)UpDownQty5.getValue();
        String Uname=labUname.getText().trim();
        int total;
        
        total=850*qty;
        
        try
        {
            Home H = new Home();
            H.AddCart(Item,qty,total,Uname);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        
        dispose();
    }//GEN-LAST:event_btnAddCart5ActionPerformed

    private void btnAddCart6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCart6ActionPerformed
        // TODO add your handling code here:
        
        String Item="Cinnamon Caramel Cream Cold Brew";
        int qty=(int)UpDownQty6.getValue();
        String Uname=labUname.getText().trim();
        int total;
        
        total=600*qty;
        
        try
        {
            Home H = new Home();
            H.AddCart(Item,qty,total,Uname);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        
        dispose();
    }//GEN-LAST:event_btnAddCart6ActionPerformed

    private void btnAddCart7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCart7ActionPerformed
        // TODO add your handling code here:
        
        String Item="Iced Mango Latte";
        int qty=(int)UpDownQty7.getValue();
        String Uname=labUname.getText().trim();
        int total;
        
        total=800*qty;
        
        try
        {
            Home H = new Home();
            H.AddCart(Item,qty,total,Uname);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        
        dispose();
    }//GEN-LAST:event_btnAddCart7ActionPerformed

    private void btnAddCart8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCart8ActionPerformed
        // TODO add your handling code here:
        
        String Item="White Chocolate Mocha";
        int qty=(int)UpDownQty8.getValue();
        String Uname=labUname.getText().trim();
        int total;
        
        total=700*qty;
        
        try
        {
            Home H = new Home();
            H.AddCart(Item,qty,total,Uname);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        
        dispose();
    }//GEN-LAST:event_btnAddCart8ActionPerformed

    private void ReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportMouseClicked
        // TODO add your handling code here:
        try
        {
        JasperDesign jd=JRXmlLoader.load("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/View/OrderReport.jrxml");
        JRDesignQuery JRDQ=new JRDesignQuery();
        JRDQ.setText("SELECT * from OrderD");
        jd.setQuery(JRDQ);
        JasperReport report=JasperCompileManager.compileReport(jd);
        JasperPrint print=JasperFillManager.fillReport(report,null,MyDBConn.getMyDBCon());
        JasperViewer.viewReport(print);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_ReportMouseClicked

    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Report;
    private javax.swing.JSpinner UpDownQty1;
    private javax.swing.JSpinner UpDownQty2;
    private javax.swing.JSpinner UpDownQty3;
    private javax.swing.JSpinner UpDownQty4;
    private javax.swing.JSpinner UpDownQty5;
    private javax.swing.JSpinner UpDownQty6;
    private javax.swing.JSpinner UpDownQty7;
    private javax.swing.JSpinner UpDownQty8;
    private javax.swing.JButton btnAddCart1;
    private javax.swing.JButton btnAddCart2;
    private javax.swing.JButton btnAddCart3;
    private javax.swing.JButton btnAddCart4;
    private javax.swing.JButton btnAddCart5;
    private javax.swing.JButton btnAddCart6;
    private javax.swing.JButton btnAddCart7;
    private javax.swing.JButton btnAddCart8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labCart;
    private javax.swing.JLabel labProfile;
    public javax.swing.JLabel labUname;
    // End of variables declaration//GEN-END:variables
}
