/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import Model.MyDBConn;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author thisajamudalige
 */
public class OrderView extends javax.swing.JFrame {

    /**
     * Creates new form OrderView
     */
    public OrderView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pay = new javax.swing.ButtonGroup();
        labTotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtOtdCusName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtOrdCardNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrdAddress = new javax.swing.JTextArea();
        rbtnCard = new javax.swing.JRadioButton();
        rbtnCash = new javax.swing.JRadioButton();
        txtOrdPhoneNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtOrdCardHolName = new javax.swing.JTextField();
        labBack = new javax.swing.JLabel();
        btnPlaceOrder = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labUname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(610, 540));
        getContentPane().setLayout(null);

        labTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        labTotal.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(labTotal);
        labTotal.setBounds(420, 270, 100, 20);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 0));
        jLabel10.setText("Total Price (Rs) :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(270, 270, 110, 19);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Customer Name : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 80, 130, 19);

        txtOtdCusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtdCusNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtOtdCusName);
        txtOtdCusName.setBounds(270, 80, 271, 30);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Address :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 130, 65, 19);

        txtOrdCardNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrdCardNumActionPerformed(evt);
            }
        });
        getContentPane().add(txtOrdCardNum);
        txtOrdCardNum.setBounds(270, 400, 271, 30);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Phone Number :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 220, 109, 19);

        txtOrdAddress.setColumns(20);
        txtOrdAddress.setRows(3);
        jScrollPane1.setViewportView(txtOrdAddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(270, 130, 271, 73);

        pay.add(rbtnCard);
        rbtnCard.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        rbtnCard.setForeground(new java.awt.Color(0, 102, 0));
        rbtnCard.setText("Card");
        rbtnCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnCardMouseClicked(evt);
            }
        });
        rbtnCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCardActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnCard);
        rbtnCard.setBounds(400, 310, 56, 23);

        pay.add(rbtnCash);
        rbtnCash.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        rbtnCash.setForeground(new java.awt.Color(0, 102, 0));
        rbtnCash.setText("Cash");
        rbtnCash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnCashMouseClicked(evt);
            }
        });
        rbtnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCashActionPerformed(evt);
            }
        });
        rbtnCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbtnCashKeyPressed(evt);
            }
        });
        getContentPane().add(rbtnCash);
        rbtnCash.setBounds(310, 310, 58, 23);

        txtOrdPhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrdPhoneNumActionPerformed(evt);
            }
        });
        getContentPane().add(txtOrdPhoneNum);
        txtOrdPhoneNum.setBounds(270, 220, 271, 29);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Cardholder Name :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 360, 127, 19);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 0));
        jLabel5.setText("Card Number :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 400, 99, 19);
        getContentPane().add(txtOrdCardHolName);
        txtOrdCardHolName.setBounds(270, 350, 271, 30);

        labBack.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        labBack.setForeground(new java.awt.Color(0, 102, 0));
        labBack.setText("<Back");
        labBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labBackMouseClicked(evt);
            }
        });
        getContentPane().add(labBack);
        labBack.setBounds(550, 10, 43, 19);

        btnPlaceOrder.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(0, 102, 0));
        btnPlaceOrder.setText("Place the Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlaceOrder);
        btnPlaceOrder.setBounds(420, 470, 134, 25);

        btnCancel.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 102, 0));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(70, 470, 134, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/pngwingcom-1 (3).png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 10, 75, 75);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 0));
        jLabel7.setText("Your Order");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 30, 122, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/thisajamudalige/Downloads/Java Applications/Starbucks/src/Untitled (1).jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 610, 530);
        getContentPane().add(labUname);
        labUname.setBounds(440, 10, 90, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtOtdCusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtdCusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtdCusNameActionPerformed

    private void txtOrdCardNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrdCardNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrdCardNumActionPerformed

    private void txtOrdPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrdPhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrdPhoneNumActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        
        String Uname=labUname.getText().trim();
        try 
        {
            Statement st=MyDBConn.getMyDBCon().createStatement();
            String sql = "DELETE FROM Cart WHERE Username='"+Uname+"'";
            
            st.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(null, "Your Order is cancelled");
            
            HomeView HV = new HomeView();
            HV.labUname.setText(Uname);
            HV.setVisible(true);
            dispose();
            
        } 
        catch (Exception e) 
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        String CusName = txtOtdCusName.getText().trim();
        String PATTERN = "^[A-Za-z ]+$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(CusName);
        
        
        if (!match.matches()) 
        {
            JOptionPane.showMessageDialog(null, "Invalid Customer Name. Please enter again.");
            return; 
        }
        
        String OrdAdd = txtOrdAddress.getText().trim();
        
        if (OrdAdd.isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Please enter Order Address.");
            return; 
        }
        
        String OrdPNum = txtOrdPhoneNum.getText().trim();
        String phonePattern = "^\\d{10}$";
        Pattern patt1 = Pattern.compile(phonePattern);
        Matcher match1 = patt1.matcher(OrdPNum);

        if (OrdPNum.isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Phone number can't be blank. Please enter a phone number.");
            return;
        }
        
        if (OrdPNum.charAt(0) != '0'|| !match1.matches()) 
        {
            JOptionPane.showMessageDialog(null, "Invalid Phone Number. Please enter a valid number.");
            return;
        }
        
        int OPNum = Integer.parseInt(OrdPNum);
        
        String pay = "";
        String CardHoldName = txtOrdCardHolName.getText().trim();
        String CardNum = txtOrdCardNum.getText().trim();
        if (rbtnCard.isSelected()) 
        {
            pay = "Card";
            
            
            String cardHolPATTERN = "^[A-Za-z ]+$";
            Pattern patt2 = Pattern.compile(cardHolPATTERN);
            Matcher match2 = patt2.matcher(CardHoldName);
        
            if (!match2.matches()) 
            {
                JOptionPane.showMessageDialog(null, "Invalid Card Holder Name. Please enter again.");
                return; 
            }

            
            String cardNumPattern = "^\\d{16}$";
            Pattern patt4 = Pattern.compile(cardNumPattern);
            Matcher match4 = patt4.matcher(CardNum);

            if (CardNum.isEmpty() || !match4.matches()) 
            {
                JOptionPane.showMessageDialog(null, "Invalid Card Number. Card Number must have 16 numbers.");
                return; 
            } 
        } 
        else if (rbtnCash.isSelected()) 
        {
            pay = "Cash"; 
        } 
        else 
        {
            JOptionPane.showMessageDialog(null, "Please select a payment type");
            return; 
        }
        
        LocalDate currentDate = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String Date = currentDate.format(formatter);
        
        String Total = labTotal.getText().trim();
        String Uname = labUname.getText().trim();
        
        try
        {
            
            Order ord = new Order();
            ord.Order(CusName,OrdAdd,OPNum,Total,pay,CardHoldName,CardNum,Date,Uname);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        
        dispose();
        
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void rbtnCashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtnCashKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCashKeyPressed

    private void rbtnCashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnCashMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCashMouseClicked

    private void rbtnCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnCardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCardMouseClicked

    private void rbtnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCashActionPerformed
        // TODO add your handling code here:
        txtOrdCardHolName.setText(null);
        txtOrdCardNum.setText(null);
        
        txtOrdCardHolName.setEditable(false);
        txtOrdCardNum.setEditable(false);
    }//GEN-LAST:event_rbtnCashActionPerformed

    private void rbtnCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCardActionPerformed
        // TODO add your handling code here:
        
        
        txtOrdCardHolName.setEditable(true);
        txtOrdCardNum.setEditable(true);
    }//GEN-LAST:event_rbtnCardActionPerformed

    private void labBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labBackMouseClicked
        // TODO add your handling code here:
        
        String Uname=labUname.getText().trim();
        
        CartView CV = new CartView();
        CV.labUname.setText(Uname);
        CV.setVisible(true);
        dispose();
    }//GEN-LAST:event_labBackMouseClicked
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labBack;
    public javax.swing.JLabel labTotal;
    public javax.swing.JLabel labUname;
    private javax.swing.ButtonGroup pay;
    private javax.swing.JRadioButton rbtnCard;
    private javax.swing.JRadioButton rbtnCash;
    private javax.swing.JTextArea txtOrdAddress;
    private javax.swing.JTextField txtOrdCardHolName;
    private javax.swing.JTextField txtOrdCardNum;
    private javax.swing.JTextField txtOrdPhoneNum;
    private javax.swing.JTextField txtOtdCusName;
    // End of variables declaration//GEN-END:variables
}
